import { type ChangeEvent, type FormEvent, useMemo, useState } from 'react';
import { Button, Field, Notice, PageHeader, errorMessage } from '../components';
import { useImportContent, useLibraries, usePreviewImport } from '../hooks';
import type { ContentType, ImportItem, ImportResult } from '../types';
import { CONTENT_TYPES } from '../types';

export function ImportPage() {
  const libraries = useLibraries(); const preview = usePreviewImport(); const importer = useImportContent();
  const [mode, setMode] = useState<'text' | 'json'>('text'); const [title, setTitle] = useState(''); const [content, setContent] = useState(''); const [jsonText, setJsonText] = useState(''); const [contentType, setContentType] = useState<ContentType>('document'); const [libraryId, setLibraryId] = useState(''); const [parseError, setParseError] = useState(''); const [items, setItems] = useState<ImportItem[]>([]); const [result, setResult] = useState<ImportResult | null>(null);
  const currentItems = useMemo(() => mode === 'text' ? title.trim() && content.trim() ? [{ title: title.trim(), content, contentType, source: 'local-ui', sourceIdentifier: `local-ui:${crypto.randomUUID()}`, metadata: { importedBy: 'local-ui' } }] : [] : items, [mode, title, content, contentType, items]);
  function parseJson(value: string) { setJsonText(value); setParseError(''); try { const parsed: unknown = JSON.parse(value); const candidate = Array.isArray(parsed) ? parsed : typeof parsed === 'object' && parsed && 'items' in parsed ? (parsed as { items: unknown }).items : [parsed]; if (!Array.isArray(candidate) || candidate.some((item) => !item || typeof item !== 'object' || typeof (item as { title?: unknown }).title !== 'string')) throw new Error('JSON must contain objects with a title field.'); setItems(candidate as ImportItem[]); } catch (error) { setItems([]); setParseError(errorMessage(error, 'Invalid JSON.')); } }
  async function fileChange(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; parseJson(await file.text()); }
  async function submitPreview(event: FormEvent) { event.preventDefault(); setResult(null); if (!currentItems.length) { setParseError('Add at least one valid item before previewing.'); return; } await preview.mutateAsync({ items: currentItems, libraryId: libraryId || undefined }); }
  async function runImport() { const imported = await importer.mutateAsync({ items: currentItems, libraryId: libraryId || undefined }); setResult(imported); }
  return <section className="workspace-page"><PageHeader eyebrow="FIG. 02 / INGEST" title="Import" description="Preview manual text or supported JSON batches before committing them to local memory." />
    <div className="import-layout"><form className="panel import-form" onSubmit={(event) => void submitPreview(event)}><div className="mode-switch" role="group" aria-label="Import source"><button type="button" className={mode === 'text' ? 'active' : ''} onClick={() => setMode('text')}>Manual text</button><button type="button" className={mode === 'json' ? 'active' : ''} onClick={() => setMode('json')}>JSON / file batch</button></div>
      <Field label="Destination library"><select value={libraryId} onChange={(event) => setLibraryId(event.target.value)}><option value="">Personal memory</option>{libraries.data?.map((library) => <option key={library.id} value={library.id}>{library.name}</option>)}</select></Field>
      <Field label="Content type"><select value={contentType} onChange={(event) => setContentType(event.target.value as ContentType)}>{CONTENT_TYPES.map((type) => <option key={type} value={type}>{type}</option>)}</select></Field>
      {mode === 'text' ? <><Field label="Title"><input required value={title} onChange={(event) => setTitle(event.target.value)} /></Field><Field label="Content"><textarea required rows={16} value={content} onChange={(event) => setContent(event.target.value)} placeholder="Paste a note, transcript, page, or document…" /></Field></> : <><Field label="Choose JSON file" hint="A JSON array or an object with an items array"><input type="file" accept="application/json,.json" onChange={(event) => void fileChange(event)} /></Field><Field label="JSON data"><textarea rows={16} value={jsonText} onChange={(event) => parseJson(event.target.value)} placeholder={'[{"title":"Decision", "content":"…", "source":"codex"}]'} /></Field></>}
      {parseError ? <Notice kind="error">{parseError}</Notice> : null}{preview.error ? <Notice kind="error">{errorMessage(preview.error, 'Preview failed.')}</Notice> : null}<Button type="submit" disabled={preview.isPending}>{preview.isPending ? 'Checking…' : 'Preview import'}</Button></form>
      <aside className="panel import-preview"><header className="panel-head"><div><span className="figure">VALIDATION PLATE</span><h2>Preview</h2></div><span>{preview.data?.rowCount ?? currentItems.length} rows</span></header>{!preview.data ? <p className="empty-copy">Build the import on the left, then preview it against the server’s validated content contract.</p> : <><div className="preview-list">{preview.data.sample.map((item, index) => <article key={`${item.title}-${index}`}><span>{String(index + 1).padStart(2, '0')}</span><div><strong>{item.title}</strong><small>{item.contentType ?? item.content_type ?? contentType} · {item.source ?? 'local-ui'}</small><p>{item.content?.slice(0, 180) || 'No text projection'}</p></div></article>)}</div><Button onClick={() => void runImport()} disabled={importer.isPending}>{importer.isPending ? 'Importing…' : `Import ${preview.data.rowCount} item${preview.data.rowCount === 1 ? '' : 's'}`}</Button></>}{result ? <div className="import-result"><Notice kind={result.failedItems ? 'error' : 'success'}>{result.completedItems} imported · {result.failedItems} failed</Notice>{result.failures.length ? <ul>{result.failures.map((failure) => <li key={failure.rowIndex}>Row {failure.rowIndex + 1}: {failure.error}</li>)}</ul> : null}</div> : null}</aside>
    </div>
  </section>;
}
