import { type FormEvent, useState } from 'react';
import { Link, NavLink, useParams } from 'react-router-dom';
import { Button, ConfirmDialog, Dialog, EmptyState, Field, LoadingState, Notice, PageHeader, SubmitForm, errorMessage, formatDate } from '../components';
import { useContent, useCreateLibrary, useDeleteLibrary, useLibraries, useLibrary, useLibraryMembers, usePreviewLibrary, useSetLibraryMembership, useTags, useUpdateLibrary } from '../hooks';
import type { FilterCondition, Library, LibraryFilter } from '../types';
import { AuditPanel, DashboardsPanel, RecipesPanel, ReportsPanel } from './LibraryAdvanced';

export function LibrariesPage() {
  const libraries = useLibraries(); const create = useCreateLibrary(); const update = useUpdateLibrary(); const remove = useDeleteLibrary();
  const [editing, setEditing] = useState<Library | 'new' | null>(null); const [deleting, setDeleting] = useState<Library | null>(null);
  function deleteSelected() { if (!deleting) return; remove.mutate(deleting.id, { onSuccess: () => setDeleting(null) }); }
  return <section className="workspace-page"><PageHeader eyebrow="FIG. 04 / WORKSPACES" title="Libraries" description="Create focused collections from reusable filters and explicit content overrides." actions={<Button onClick={() => setEditing('new')}>Create library</Button>} />
    {libraries.error ? <Notice kind="error">{errorMessage(libraries.error, 'Unable to load libraries.')}</Notice> : null}{libraries.isLoading ? <LoadingState label="Loading libraries" /> : null}
    {!libraries.isLoading && !libraries.data?.length ? <EmptyState title="No libraries found">The system all-content library is created during local setup.</EmptyState> : null}
    <div className="library-grid">{libraries.data?.map((library) => <article className="library-card" key={library.id}><header><span className="figure">{library.kind === 'system_all_content' ? 'SYSTEM LIBRARY' : 'CUSTOM LIBRARY'}</span><h2>{library.name}</h2><span className="library-count">{library.itemCount}</span></header><p>{library.description || 'No description'}</p><dl><dt>Slug</dt><dd>{library.slug}</dd><dt>Filter rules</dt><dd>{library.filter?.conditions.length ?? 0}</dd><dt>Updated</dt><dd>{formatDate(library.updatedAt)}</dd></dl><footer><Link className="button primary" to={`/libraries/${library.id}`}>Open library</Link>{library.kind === 'user_defined' ? <><Button variant="secondary" onClick={() => setEditing(library)}>Edit</Button><Button variant="danger" onClick={() => setDeleting(library)}>Delete</Button></> : null}</footer></article>)}</div>
    <LibraryForm key={editing === 'new' ? 'new' : editing?.id ?? 'closed'} open={Boolean(editing)} library={editing === 'new' ? undefined : editing ?? undefined} busy={create.isPending || update.isPending} error={editing === 'new' ? create.error : update.error} onClose={() => setEditing(null)} onSubmit={async (input) => { try { if (editing === 'new') await create.mutateAsync(input); else if (editing) await update.mutateAsync({ id: editing.id, input }); setEditing(null); } catch { /* The mutation error stays visible and the form remains open. */ } }} />
    <ConfirmDialog open={Boolean(deleting)} title="Delete library?" busy={remove.isPending} onClose={() => setDeleting(null)} onConfirm={deleteSelected}>The custom library “{deleting?.name}” will be deactivated. Content records will not be deleted.{remove.error ? <Notice kind="error">{errorMessage(remove.error, 'Unable to delete the library.')}</Notice> : null}</ConfirmDialog>
  </section>;
}

export function LibraryPage() {
  const { libraryId, section = 'members' } = useParams(); const library = useLibrary(libraryId);
  if (library.isLoading) return <section className="workspace-page"><LoadingState label="Loading library" /></section>;
  if (library.error || !library.data) return <section className="workspace-page"><Notice kind="error">{errorMessage(library.error, 'Library not found.')}</Notice></section>;
  const base = `/libraries/${library.data.id}`;
  return <section className="workspace-page"><PageHeader eyebrow="FIG. 04A / LIBRARY" title={library.data.name} description={library.data.description || 'A focused workspace over local content.'} actions={<Link className="button primary" to={`${base}/answers`}>Ask this library</Link>} /><div className="subnav library-subnav"><NavLink end to={base}>Members</NavLink><NavLink to={`${base}/overview`}>Overview & filter</NavLink><NavLink to={`${base}/recipes`}>Recipes</NavLink><NavLink to={`${base}/reports`}>Reports</NavLink><NavLink to={`${base}/dashboards`}>Dashboards</NavLink><NavLink to={`${base}/audit`}>Audit</NavLink><NavLink to="/settings">Tokens & settings</NavLink><NavLink to="/libraries">All libraries</NavLink></div>{section === 'members' ? <LibraryMembers library={library.data} /> : section === 'overview' ? <LibraryOverview library={library.data} /> : section === 'recipes' ? <RecipesPanel libraryId={library.data.id} /> : section === 'reports' ? <ReportsPanel libraryId={library.data.id} /> : section === 'dashboards' ? <DashboardsPanel libraryId={library.data.id} /> : section === 'audit' ? <AuditPanel libraryId={library.data.id} /> : <Notice kind="error">Unknown library section.</Notice>}</section>;
}

function LibraryMembers({ library }: { library: Library }) {
  const [search, setSearch] = useState(''); const [query, setQuery] = useState(''); const [cursorHistory, setCursorHistory] = useState<Array<string | undefined>>([undefined]);
  const members = useLibraryMembers(library.id, query, cursorHistory[cursorHistory.length - 1]); const override = useSetLibraryMembership(); const content = useContent({ search, limit: 10 });
  const pageError = members.error ?? content.error ?? override.error;
  return <div className="library-layout"><section className="panel"><header className="panel-head"><div><span className="figure">EFFECTIVE MEMBERS</span><h2>{library.itemCount} records</h2></div><form className="inline-form" onSubmit={(event) => { event.preventDefault(); setQuery(search); setCursorHistory([undefined]); }}><input aria-label="Search library members" placeholder="Search this library…" value={search} onChange={(event) => setSearch(event.target.value)} /><Button type="submit">Search</Button></form></header>{pageError ? <Notice kind="error">{errorMessage(pageError, 'Unable to update library membership.')}</Notice> : null}{members.isLoading ? <LoadingState /> : <div className="member-list">{members.data?.items.map((item) => <article key={item.id}><div><strong>{item.title}</strong><small>{item.contentType} · {item.source} · {formatDate(item.createdAt)}</small><p>{item.summary}</p></div>{library.kind === 'user_defined' ? <Button variant="danger" onClick={() => override.mutate({ libraryId: library.id, contentId: item.id, mode: 'exclude', active: true })}>Exclude</Button> : null}</article>)}</div>}<div className="pagination"><Button variant="secondary" disabled={cursorHistory.length === 1} onClick={() => setCursorHistory((value) => value.slice(0, -1))}>Previous</Button><Button variant="secondary" disabled={!members.data?.hasMore || !members.data.nextCursor} onClick={() => setCursorHistory((value) => [...value, members.data?.nextCursor ?? undefined])}>Next</Button></div></section>{library.kind === 'user_defined' ? <aside className="panel"><header className="panel-head"><div><span className="figure">MANUAL OVERRIDES</span><h2>Include content</h2></div></header><div className="compact-list">{content.data?.items.map((item) => <article key={item.id}><div className="table-link"><strong>{item.title}</strong><small>{item.source} · {item.contentType}</small></div><Button variant="secondary" onClick={() => override.mutate({ libraryId: library.id, contentId: item.id, mode: 'include', active: true })}>Include</Button></article>)}</div></aside> : null}</div>;
}

function LibraryOverview({ library }: { library: Library }) {
  const update = useUpdateLibrary(); const preview = usePreviewLibrary(); const tags = useTags(); const [filter, setFilter] = useState<LibraryFilter | null>(library.filter); const [field, setField] = useState<FilterCondition['field']>('source'); const [operator, setOperator] = useState<FilterCondition['operator']>('eq'); const [value, setValue] = useState('');
  const isSystem = library.kind === 'system_all_content';
  function addRule(event: FormEvent) { event.preventDefault(); if (!value.trim()) return; const condition: FilterCondition = { field, operator, value: operator === 'in' ? value.split(',').map((entry) => entry.trim()).filter(Boolean) : value.trim() }; setFilter((current) => ({ operator: current?.operator ?? 'and', conditions: [...(current?.conditions ?? []), condition] })); setValue(''); }
  const mutationError = update.error ?? preview.error;
  return <div className="panel filter-editor"><header className="panel-head"><div><span className="figure">MEMBERSHIP MODEL</span><h2>{isSystem ? 'All local content' : 'Filter builder'}</h2></div>{!isSystem ? <div className="page-actions"><Button variant="secondary" onClick={() => preview.mutate({ id: library.id, filter })}>Preview</Button><Button onClick={() => update.mutate({ id: library.id, input: { filter } })}>Save filter</Button></div> : null}</header>{mutationError ? <Notice kind="error">{errorMessage(mutationError, 'Unable to update the library filter.')}</Notice> : null}{isSystem ? <Notice>This protected system library includes all non-deleted local content and cannot be edited or deleted.</Notice> : <><div className="filter-operator"><span>Match</span><select value={filter?.operator ?? 'and'} onChange={(event) => setFilter((current) => ({ operator: event.target.value as 'and' | 'or', conditions: current?.conditions ?? [] }))}><option value="and">all rules</option><option value="or">any rule</option></select></div><div className="rule-list">{filter?.conditions.map((condition, index) => <article key={`${condition.field}-${index}`}><code>{condition.field}</code><span>{condition.operator}</span><strong>{Array.isArray(condition.value) ? condition.value.join(', ') : String(condition.value)}</strong><Button variant="quiet" onClick={() => setFilter((current) => current ? { ...current, conditions: current.conditions.filter((_, itemIndex) => itemIndex !== index) } : null)}>Remove</Button></article>)}</div><form className="rule-form" onSubmit={addRule}><Field label="Field"><select value={field} onChange={(event) => setField(event.target.value as FilterCondition['field'])}><option value="source">Source</option><option value="content_type">Content type</option><option value="tag">Tag</option><option value="created_at">Created date</option></select></Field><Field label="Operator"><select value={operator} onChange={(event) => setOperator(event.target.value as FilterCondition['operator'])}><option value="eq">Equals</option><option value="in">Any of</option><option value="contains">Contains</option><option value="gte">On/after</option><option value="lte">On/before</option></select></Field><Field label="Value"><input list={field === 'tag' ? 'tag-options' : undefined} value={value} onChange={(event) => setValue(event.target.value)} placeholder={operator === 'in' ? 'Comma-separated values' : 'Value'} />{field === 'tag' ? <datalist id="tag-options">{tags.data?.map((tag) => <option key={tag.id} value={tag.slug} />)}</datalist> : null}</Field><Button type="submit">Add rule</Button></form>{preview.data ? <Notice kind="success">Preview matched {preview.data.items.length}{preview.data.hasMore ? '+' : ''} records.</Notice> : null}</>}</div>;
}

function LibraryForm({ open, library, busy, error, onClose, onSubmit }: { open: boolean; library?: Library; busy: boolean; error: unknown; onClose(): void; onSubmit(input: { name: string; slug: string; description: string | null; filter: LibraryFilter | null }): Promise<void> }) {
  const [name, setName] = useState(library?.name ?? ''); const [slug, setSlug] = useState(library?.slug ?? ''); const [description, setDescription] = useState(library?.description ?? '');
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); await onSubmit({ name: name.trim(), slug: slug || slugify(name), description: description || null, filter: library?.filter ?? null }); }
  return <Dialog open={open} title={library ? 'Edit library' : 'Create library'} onClose={onClose}><SubmitForm onSubmit={(event) => void submit(event)}>{error ? <Notice kind="error">{errorMessage(error, 'Unable to save the library.')}</Notice> : null}<Field label="Name"><input required value={name} onChange={(event) => setName(event.target.value)} /></Field><Field label="Slug"><input pattern="[a-z0-9]+(?:-[a-z0-9]+)*" value={slug} onChange={(event) => setSlug(event.target.value)} /></Field><Field label="Description"><textarea rows={4} value={description} onChange={(event) => setDescription(event.target.value)} /></Field><div className="dialog-actions"><Button type="button" variant="secondary" onClick={onClose}>Cancel</Button><Button type="submit" disabled={busy}>{busy ? 'Saving…' : 'Save library'}</Button></div></SubmitForm></Dialog>;
}
function slugify(value: string) { return value.trim().toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 120); }
