import { type FormEvent, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { downloadTextFile, rowsToCsv } from '../api';
import { Button, ConfirmDialog, Dialog, Field, LoadingState, Notice, PageHeader, SubmitForm, errorMessage, formatDate } from '../components';
import { useAccessTokens, useAudit, useCreateAccessToken, useLibraries, useRevokeAccessToken, useSettings, useUpdateAccessToken, useUpdateSettings } from '../hooks';
import type { AccessToken, MintedAccessToken } from '../types';
import type { WebSettingsExtension } from '../composition';

export function SettingsPage({ extensionSections = [] }: { readonly extensionSections?: readonly WebSettingsExtension[] }) {
  return <section className="workspace-page"><PageHeader eyebrow="FIG. 07 / LOCAL OWNER" title="Settings" description="Configure neutral workspace preferences, agent access, and inspect local activity without exposing provider credentials." /><div className="settings-grid"><PreferencesPanel /><TokenPanel /><section className="panel guidance-panel"><span className="figure">WORKSPACE LINKS</span><h2>Local administration</h2><p>Tags, access tokens, and audit history belong to the local owner. Model provider credentials remain installer-managed and are never returned to this browser.</p><div className="page-actions"><Link className="button secondary" to="/tags">Manage tags</Link><a className="button secondary" href="https://github.com/the-answerai/answer-engine#configuration" target="_blank" rel="noreferrer">Model configuration guide</a></div></section>{extensionSections.map((section) => <section className="panel" key={section.id} aria-label={section.title}><header className="panel-head"><div><span className="figure">EXTENSION</span><h2>{section.title}</h2></div></header>{section.element}</section>)}<WorkspaceAudit /></div></section>;
}

function PreferencesPanel() {
  const settings = useSettings(); const update = useUpdateSettings(); const libraries = useLibraries(); const [pageSize, setPageSize] = useState(25); const [libraryId, setLibraryId] = useState(''); const [density, setDensity] = useState<'comfortable' | 'compact'>('comfortable'); const [format, setFormat] = useState<'json' | 'csv' | 'markdown'>('json');
  useEffect(() => { if (!settings.data) return; setPageSize(settings.data.defaultPageSize); setLibraryId(settings.data.defaultLibraryId ?? ''); setDensity(settings.data.density); setFormat(settings.data.defaultExportFormat); }, [settings.data]);
  return <section className="panel"><header className="panel-head"><div><span className="figure">PREFERENCES</span><h2>Workspace defaults</h2></div></header>{settings.isLoading ? <LoadingState /> : <SubmitForm onSubmit={(event) => { event.preventDefault(); update.mutate({ defaultPageSize: pageSize, defaultLibraryId: libraryId || null, density, defaultExportFormat: format }); }}>{settings.error || update.error ? <Notice kind="error">{errorMessage(settings.error ?? update.error, 'Unable to save settings.')}</Notice> : null}{update.isSuccess ? <Notice kind="success">Settings saved.</Notice> : null}<Field label="Default page size"><select value={pageSize} onChange={(event) => setPageSize(Number(event.target.value))}><option value={10}>10</option><option value={25}>25</option><option value={50}>50</option><option value={100}>100</option></select></Field><Field label="Default library"><select value={libraryId} onChange={(event) => setLibraryId(event.target.value)}><option value="">All content</option>{libraries.data?.map((library) => <option key={library.id} value={library.id}>{library.name}</option>)}</select></Field><Field label="Density"><select value={density} onChange={(event) => setDensity(event.target.value as typeof density)}><option value="comfortable">Comfortable</option><option value="compact">Compact</option></select></Field><Field label="Default export"><select value={format} onChange={(event) => setFormat(event.target.value as typeof format)}><option value="json">JSON</option><option value="csv">CSV</option><option value="markdown">Markdown</option></select></Field><Button type="submit" disabled={update.isPending}>{update.isPending ? 'Saving…' : 'Save settings'}</Button></SubmitForm>}</section>;
}

function TokenPanel() {
  const tokens = useAccessTokens(); const create = useCreateAccessToken(); const update = useUpdateAccessToken(); const revoke = useRevokeAccessToken(); const [createOpen, setCreateOpen] = useState(false); const [editing, setEditing] = useState<AccessToken>(); const [revoking, setRevoking] = useState<AccessToken>(); const [minted, setMinted] = useState<MintedAccessToken>(); const [copied, setCopied] = useState(false);
  async function copyToken() { if (!minted) return; try { await navigator.clipboard.writeText(minted.token); setCopied(true); } catch { setCopied(false); } }
  useEffect(() => { if (!minted) create.reset(); }, [minted]);
  return <section className="panel token-panel" id="tokens"><header className="panel-head"><div><span className="figure">AGENT ACCESS</span><h2>Access tokens</h2></div><Button onClick={() => setCreateOpen(true)}>Mint token</Button></header>{tokens.error || create.error || update.error || revoke.error ? <Notice kind="error">{errorMessage(tokens.error ?? create.error ?? update.error ?? revoke.error, 'The token action failed.')}</Notice> : null}{minted ? <Notice kind="success"><strong>Copy this token now. It will not be shown again.</strong><code className="secret-value">{minted.token}</code><div className="page-actions"><Button onClick={() => void copyToken()}>{copied ? 'Copied' : 'Copy token'}</Button><Button variant="quiet" onClick={() => setMinted(undefined)}>Dismiss forever</Button></div><small>Setup: <code>export ANSWER_ENGINE_API_KEY=&quot;{minted.token}&quot;</code></small></Notice> : null}{tokens.isLoading ? <LoadingState /> : <div className="token-list">{tokens.data?.map((token) => <article key={token.id}><div><strong>{token.name}</strong><code>{token.keyPrefix}…</code><small>{token.libraryId ? 'Library scoped' : 'Tenant scoped'} · {token.capabilities.join(' + ')} · created {formatDate(token.createdAt)}</small><small>{token.isProtected ? 'Protected installer credential' : token.isCurrent ? 'Authenticating this session' : token.revokedAt ? `Revoked ${formatDate(token.revokedAt)}` : token.expiresAt ? `Expires ${formatDate(token.expiresAt)}` : 'No expiry'}</small></div>{!token.revokedAt && !token.isProtected && !token.isCurrent ? <div className="page-actions"><Button variant="secondary" onClick={() => setEditing(token)}>Edit</Button><Button variant="danger" onClick={() => setRevoking(token)}>Revoke</Button></div> : null}</article>)}</div>}<TokenCreateForm open={createOpen} create={create} onClose={() => setCreateOpen(false)} onCreated={(value) => { setMinted(value); setCreateOpen(false); }} /><TokenEditForm token={editing} onClose={() => setEditing(undefined)} onSave={async (input) => { if (!editing) return; try { await update.mutateAsync({ id: editing.id, input }); setEditing(undefined); } catch { /* keep dialog */ } }} /><ConfirmDialog open={Boolean(revoking)} title="Revoke access token?" confirmLabel="Revoke token" busy={revoke.isPending} onClose={() => setRevoking(undefined)} onConfirm={() => revoking && revoke.mutate(revoking.id, { onSuccess: () => setRevoking(undefined) })}>Agents using “{revoking?.name}” will immediately lose access. This cannot be undone.</ConfirmDialog></section>;
}

function TokenCreateForm({ open, create, onClose, onCreated }: { open: boolean; create: ReturnType<typeof useCreateAccessToken>; onClose(): void; onCreated(token: MintedAccessToken): void }) {
  const libraries = useLibraries(); const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [libraryId, setLibraryId] = useState(''); const [read, setRead] = useState(true); const [write, setWrite] = useState(false); const [expiresAt, setExpiresAt] = useState('');
  async function submit(event: FormEvent) { event.preventDefault(); try { const value = await create.mutateAsync({ name: name.trim(), description: description || null, libraryId: libraryId || null, capabilities: [...(read ? ['read' as const] : []), ...(write ? ['write' as const] : [])], expiresAt: expiresAt ? new Date(`${expiresAt}T23:59:59.999Z`).toISOString() : null }); onCreated(value); } catch { /* keep form */ } }
  return <Dialog open={open} title="Mint local access token" onClose={onClose}><SubmitForm onSubmit={(event) => void submit(event)}>{create.error ? <Notice kind="error">{errorMessage(create.error, 'Unable to mint token.')}</Notice> : null}<Field label="Name"><input required value={name} onChange={(event) => setName(event.target.value)} /></Field><Field label="Description"><textarea value={description} onChange={(event) => setDescription(event.target.value)} /></Field><Field label="Scope"><select value={libraryId} onChange={(event) => setLibraryId(event.target.value)}><option value="">Entire local workspace</option>{libraries.data?.map((library) => <option key={library.id} value={library.id}>{library.name}</option>)}</select></Field><fieldset><legend>Capabilities</legend><div className="check-grid"><label><input type="checkbox" checked={read} onChange={(event) => setRead(event.target.checked)} />Read</label><label><input type="checkbox" checked={write} onChange={(event) => setWrite(event.target.checked)} />Write</label></div></fieldset><Field label="Expiry"><input type="date" value={expiresAt} onChange={(event) => setExpiresAt(event.target.value)} /></Field><div className="dialog-actions"><Button type="button" variant="secondary" onClick={onClose}>Cancel</Button><Button type="submit" disabled={create.isPending || (!read && !write)}>{create.isPending ? 'Minting…' : 'Mint token'}</Button></div></SubmitForm></Dialog>;
}

function TokenEditForm({ token, onClose, onSave }: { token?: AccessToken; onClose(): void; onSave(input: { name: string; description: string | null; expiresAt: string | null }): Promise<void> }) {
  const [name, setName] = useState(token?.name ?? ''); const [description, setDescription] = useState(token?.description ?? ''); const [expiresAt, setExpiresAt] = useState(token?.expiresAt?.slice(0, 10) ?? '');
  useEffect(() => { setName(token?.name ?? ''); setDescription(token?.description ?? ''); setExpiresAt(token?.expiresAt?.slice(0, 10) ?? ''); }, [token]);
  return <Dialog open={Boolean(token)} title="Edit token metadata" onClose={onClose}><SubmitForm onSubmit={(event) => { event.preventDefault(); void onSave({ name: name.trim(), description: description || null, expiresAt: expiresAt ? new Date(`${expiresAt}T23:59:59.999Z`).toISOString() : null }); }}><Field label="Name"><input required value={name} onChange={(event) => setName(event.target.value)} /></Field><Field label="Description"><textarea value={description} onChange={(event) => setDescription(event.target.value)} /></Field><Field label="Expiry"><input type="date" value={expiresAt} onChange={(event) => setExpiresAt(event.target.value)} /></Field><div className="dialog-actions"><Button type="button" variant="secondary" onClick={onClose}>Cancel</Button><Button type="submit">Save metadata</Button></div></SubmitForm></Dialog>;
}

function WorkspaceAudit() {
  const [action, setAction] = useState(''); const [resourceType, setResourceType] = useState(''); const [cursorHistory, setCursorHistory] = useState<Array<string | undefined>>([undefined]); const [detailId, setDetailId] = useState<string>(); const audit = useAudit({ action: action || undefined, resourceType: resourceType || undefined, cursor: cursorHistory.at(-1) }); const detail = audit.data?.items.find((entry) => entry.id === detailId);
  return <section className="panel audit-panel"><header className="panel-head"><div><span className="figure">LOCAL AUDIT</span><h2>Workspace activity</h2></div><Button variant="secondary" disabled={!audit.data?.items.length} onClick={() => downloadTextFile('workspace-audit.csv', rowsToCsv((audit.data?.items ?? []) as unknown as Array<Record<string, unknown>>), 'text/csv')}>Export page CSV</Button></header><div className="filter-row"><Field label="Action"><input value={action} onChange={(event) => { setAction(event.target.value); setCursorHistory([undefined]); }} placeholder="recipe.run" /></Field><Field label="Resource type"><input value={resourceType} onChange={(event) => { setResourceType(event.target.value); setCursorHistory([undefined]); }} placeholder="recipe_run" /></Field></div>{audit.error ? <Notice kind="error">{errorMessage(audit.error, 'Unable to load audit history.')}</Notice> : null}{audit.isLoading ? <LoadingState /> : <div className="audit-list">{audit.data?.items.map((entry) => <button key={entry.id} onClick={() => setDetailId(entry.id)}><span><strong>{entry.action}</strong><small>{entry.resourceType} · {formatDate(entry.createdAt)}</small></span><span className={`status-pill ${entry.outcome}`}>{entry.outcome}</span></button>)}</div>}<div className="pagination"><Button variant="secondary" disabled={cursorHistory.length === 1} onClick={() => setCursorHistory((value) => value.slice(0, -1))}>Previous</Button><Button variant="secondary" disabled={!audit.data?.hasMore || !audit.data.nextCursor} onClick={() => setCursorHistory((value) => [...value, audit.data?.nextCursor ?? undefined])}>Next</Button></div><Dialog open={Boolean(detail)} title={detail?.action ?? 'Audit detail'} onClose={() => setDetailId(undefined)}><pre>{JSON.stringify(detail, null, 2)}</pre></Dialog></section>;
}
